name: API Deploy

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'apps/api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@master
        with:
          node-version: '16.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6

      - name: Run mp:upload
        id: upload
        run: |
          pnpm install
          pnpm --filter api build 
          pnpm --filter api deploy
