name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6

      - name: Install dependencies & build
        run: pnpm install
      - run: pnpm run build --if-present

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRES: ${{ secrets.JWT_EXPIRES }}
        run: pnpm test
