name: Upload MiniProgram
on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - shell: bash
        env:
          MP_PRIVATE_KEY: ${{ secrets.MP_PRIVATE_KEY }}
        run: |
          # TODO: skip don't exist MP_PRIVATE_KEY
          echo "$MP_PRIVATE_KEY" > private.key
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: |
        yarn
        yarn build
        yarn mp:upload
