name: PR Comment Trigger

on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    runs-on: ubuntu-latest
    steps:
      - uses: yuler/pr-comment-trigger@main
        id: 'pr'
        with:
          trigger: '/upload'
        env:
          GITHUB_TOKEN: '${{ github.token }}'
      - name: Wait 2 seconds
        run: sleep 2
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.pr.outputs.branch }}
      - name: Check `MP_PRIVATE_KEY` secret
        shell: bash
        env:
          MP_PRIVATE_KEY: ${{ secrets.MP_PRIVATE_KEY }}
        run: |
          if [[ -z $MP_PRIVATE_KEY ]]; then
            echo "##########"
            echo ""
            echo "Please set 'MP_PRIVATE_KEY' key in actions secrets"
            echo ""
            echo "##########"
            exit 1
          else
            echo "$MP_PRIVATE_KEY" > private.key
          fi
      - uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - name: Run mp:upload
        id: upload
        run: |
          npm install miniprogram-ci
          npm run build --workspace=mp --if-present
          npm run mp:upload
      - name: Comment upload result
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs')
            const result = fs.readFileSync('./upload-result.json')
            const body = '🚀  Upload Result:\n```js\n' + result + '\n```'
            github.issues.createComment({
              body,
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
