name: Upload MiniProgram
on:
  push:
    branches:
      - main
  issue_comment:
    types: ['labeled']

jobs:
  upload:
    if: ${{ github.ref == 'refs/heads/main' }} || github.event.issue.pull_request && contains(github.event.issue.body, 'upload_miniprogram')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          MP_PRIVATE_KEY: ${{ secrets.MP_PRIVATE_KEY }}
        run: |
          if [[ -z $MP_PRIVATE_KEY ]]; then
            echo "##########"
            echo ""
            echo "Please set 'MP_PRIVATE_KEY' key in actions secrets"
            echo ""
            echo "##########"
            exit 1
          else
            echo "$MP_PRIVATE_KEY" > mp/private.key
          fi
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: |
          npm ci
          npm run build --workspace mp
          npm run upload --workspace mp
